# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

is_windows <- function() .Platform$OS.type == "windows"
# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:stringstatic
# ======================================================================

`%||%` <- function(lhs, rhs) {
	if (length(lhs) == 0) return(rhs)
	lhs
}

str_detect <- function(string, pattern) {
	is_fixed <- inherits(pattern, "fixed")
	ignore.case <- attr(pattern, "options")$case_insensitive %||% FALSE

	grepl(
		pattern = pattern,
		x = string,
		ignore.case = ignore.case,
		perl = !is_fixed,
		fixed = is_fixed
	)
}

str_remove_all <- function(string, pattern) {
	str_replace_all(string, pattern, replacement = "")
}

str_replace_all <- function(string, pattern, replacement, fixed = FALSE) {
	is_fixed <- inherits(pattern, "fixed")
	ignore.case <- attr(pattern, "options")$case_insensitive %||% FALSE

	if (!is.null(names(pattern))) {
		for (i in seq_along(pattern)) {
			string <- gsub(
				pattern = names(pattern)[[i]],
				replacement = pattern[[i]],
				x = string,
				ignore.case = ignore.case,
				perl = !is_fixed,
				fixed = is_fixed
			)
		}

		return(string)
	}

	gsub(
		pattern,
		replacement,
		x = string,
		ignore.case = ignore.case,
		perl = !is_fixed,
		fixed = is_fixed
	)
}
