# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

is_windows <- function() .Platform$OS.type == "windows"

str_remove_all <- function(text, pattern) {
  str_replace_all(text, pattern = pattern, replacement = "")
}
